"""
Image generation routes - AI image creation
"""
from fastapi import APIRouter, Depends, HTTPException, status
from app.schemas.image_schema import ImageGenerateRequest, ImageResponse
from app.services.image_engine import generate_image
from app.core.security import get_current_user
from app.database.crud import save_generated_image, get_user_images, delete_image as db_delete_image

router = APIRouter()


@router.post("/generate", response_model=ImageResponse)
async def generate_ai_image(
    request: ImageGenerateRequest,
    current_user: dict = Depends(get_current_user)
):
    """
    Generate an image using AI based on a prompt
    """
    try:
        # Generate image using AI service
        image_url = await generate_image(
            prompt=request.prompt,
            size=request.size,
            style=request.style
        )
        
        # Save to database
        saved_image = await save_generated_image(
            user_id=current_user["id"],
            prompt=request.prompt,
            image_url=image_url,
            size=request.size,
            style=request.style
        )
        
        return {
            "id": saved_image["id"],
            "image_url": image_url,
            "prompt": request.prompt,
            "created_at": saved_image["created_at"]
        }
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error generating image: {str(e)}"
        )


@router.get("/my-images", response_model=list[ImageResponse])
async def get_my_images(current_user: dict = Depends(get_current_user)):
    """
    Get all images generated by the current user
    """
    images = await get_user_images(current_user["id"])
    return images


@router.get("/{image_id}", response_model=ImageResponse)
async def get_image(
    image_id: str,
    current_user: dict = Depends(get_current_user)
):
    """
    Get a specific image by ID
    """
    # TODO: Implement get single image
    raise HTTPException(
        status_code=status.HTTP_501_NOT_IMPLEMENTED,
        detail="Get single image not implemented yet"
    )


@router.delete("/{image_id}")
async def delete_image(
    image_id: str,
    current_user: dict = Depends(get_current_user)
):
    """
    Delete an image
    """
    await db_delete_image(image_id, current_user["id"])
    return {"message": "Image deleted successfully"}
